### ISSUE TITLE
getting double precision values

### ISSUE THREAD

**Issue by rmcd-mscb** [pymt-lab/pymt_prms_surface#2]
@mdpiper 

When I get a double precision value such as dprst_seep_hru or dprst_sroff_hru,  for example, 
m.var['dprst_sroff_hru'].data I get a KeyError:  'double'.  I checked the prms6 source and these are both double precision ptrs, for example: real(r64), pointer :: dprst_seep_hru(:) and in the var_type() the are both labeled 'double'.  for example:

``` FORTRAN
case( &
        "hortonian_lakes", &
        'dprst_seep_hru', 'strm_seg_in', 'pkwater_equiv', 'dprst_stor_hru', &
        'last_intcp_stor', 'hru_area_dble', 'pkwater_ante', 'dprst_in', &
        'dprst_sroff_hru','dprst_stor_ante','dprst_vol_clos','dprst_vol_open', &
        'hru_hortn_cascflow', 'hortonian_flow')
        type = "double"
        bmi_status = BMI_SUCCESS

```

**Comment by mdpiper** [comment]
The BMI variable type should match the Fortran variable type, so "double precision" instead of "double". This isn't clear at all from the BMI docs, so I'll fix that. I did change this in bmi-prms6-surface with https://github.com/nhm-usgs/bmi-prms6-surface/commit/b53e1fc2d17fd05ba095456e626f3b1a0a1a4d2b included in https://github.com/nhm-usgs/bmi-prms6-surface/pull/27.
